engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 64
    exclude_paths:
      - "config/*.js"
      - "tests/**/*.js"
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      ignore_warnings: true
  fixme:
    enabled: true
    checks:
      TODO:
        enabled: false
ratings:
  paths:
    - "**.js"
exclude_paths:
  - "vendor/**/*.js"
